const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

const Theme = {
    light: {
      text: '#000',
      background: '#fff',
      tint: tintColorLight,
      tabIconDefault: '#ccc',
      tabIconSelected: tintColorLight,
      foreground: '#000',
      card: '#fff',
      cardForeground: '#000',
      popover: '#fff',
      popoverForeground: '#000',
      primary: '#fff',
      primaryForeground: '#fff',
      secondary: '#000',
      secondaryForeground: '#fff',
      muted: '#000',
      mutedForeground: '#d3d3d3',
      accent: '#000',
      accentForeground: '#fff',
      destructive: '#e74c3c',
      destructiveForeground: '#fff',
      border: '#000',
      input: '#000',
      ring: '#000',
      radius: 10,
    },
    dark: {
      text: '#fff',
      background: '#fff',
      tint: tintColorDark,
      tabIconDefault: '#ccc',
      tabIconSelected: tintColorDark,
      foreground: '#000',
      card: '#fff',
      cardForeground: '#000',
      popover: '#fff',
      popoverForeground: '#000',
      primary: '#000',
      primaryForeground: '#fff',
      secondary: '#000',
      secondaryForeground: '#fff',
      muted: '#000',
      mutedForeground: '#fff',
      accent: '#000',
      accentForeground: '#fff',
      destructive: '#000',
      destructiveForeground: '#fff',
      border: '#000',
      input: '#000',
      ring: '#000',
      radius: 10,
    },
  };

export default Theme;